/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditableSlider: typeof import('./src/components/EditableSlider.vue')['default']
    ExportProgressDialog: typeof import('./src/components/ExportProgressDialog.vue')['default']
    HelpDialog: typeof import('./src/components/HelpDialog.vue')['default']
    PresetManager: typeof import('./src/components/PresetManager.vue')['default']
    ReverbControls: typeof import('./src/components/ReverbControls.vue')['default']
  }
}
